# Supabase Configuration

# Project ID - Replace with your actual Supabase project ID
# You can find this in your Supabase dashboard under Project Settings
project_id = "your-project-id"

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# The maximum number of rows to return from a view, table, or stored procedure.
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# The database major version to use
major_version = 15

[studio]
# Port to use for Supabase Studio
port = 54323

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used in emails.
site_url = "http://localhost:5173"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:5173"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses.
double_confirm_changes_enabled = true

# Edge Functions
[functions]
# Enable functions
enabled = true

[functions."sofifa-proxy"]
# Verify JWT tokens for this function
verify_jwt = true
