// AUTO-GENERATED: Offizielle EA FC26 Team-Liste mit Star-Ratings (halbe Sterne 0.5–5.0).
// Nationalmannschaften ohne offizielles Rating (rating: null). Frauen-Nationalteams als "… (Frauen)".
export const FC26_TEAMS = [
  { name: "Paris Saint-Germain", rating: 5.0, women: false, national: false },
  { name: "FC Barcelona", rating: 5.0, women: false, national: false },
  { name: "Real Madrid", rating: 5.0, women: false, national: false },
  { name: "FC Barcelona (W)", rating: 5.0, women: true, national: false },
  { name: "OL Lyonnes", rating: 5.0, women: false, national: false },
  { name: "Arsenal", rating: 5.0, women: false, national: false },
  { name: "Liverpool", rating: 5.0, women: false, national: false },
  { name: "Manchester City", rating: 5.0, women: false, national: false },
  { name: "Bayern", rating: 5.0, women: false, national: false },
  { name: "Inter", rating: 5.0, women: false, national: false },
  { name: "Arsenal (W)", rating: 5.0, women: true, national: false },
  { name: "Chelsea (W)", rating: 5.0, women: true, national: false },
  { name: "Bayern (W)", rating: 5.0, women: true, national: false },
  { name: "Atlético Madrid", rating: 4.5, women: false, national: false },
  { name: "Real Madrid (W)", rating: 4.5, women: true, national: false },
  { name: "Chelsea", rating: 4.5, women: false, national: false },
  { name: "Newcastle United", rating: 4.5, women: false, national: false },
  { name: "Tottenham", rating: 4.5, women: false, national: false },
  { name: "Borussia Dortmund", rating: 4.5, women: false, national: false },
  { name: "Napoli", rating: 4.5, women: false, national: false },
  { name: "Manchester City (W)", rating: 4.5, women: true, national: false },
  { name: "Aston Villa", rating: 4.5, women: false, national: false },
  { name: "Manchester United", rating: 4.5, women: false, national: false },
  { name: "Bayer Leverkusen", rating: 4.5, women: false, national: false },
  { name: "RB Leipzig", rating: 4.5, women: false, national: false },
  { name: "Juventus", rating: 4.5, women: false, national: false },
  { name: "Milan", rating: 4.5, women: false, national: false },
  { name: "Manchester United (W)", rating: 4.5, women: true, national: false },
  { name: "Nottingham Forest", rating: 4.5, women: false, national: false },
  { name: "AS Roma", rating: 4.5, women: false, national: false },
  { name: "Atalanta", rating: 4.5, women: false, national: false },
  { name: "Lazio", rating: 4.5, women: false, national: false },
  { name: "Sporting", rating: 4.5, women: false, national: false },
  { name: "Athletic Bilbao", rating: 4.5, women: false, national: false },
  { name: "Galatasaray Istanbul", rating: 4.5, women: false, national: false },
  { name: "VfL Wolfsburg (W)", rating: 4.5, women: true, national: false },
  { name: "Kansas City Current (W)", rating: 4.5, women: true, national: false },
  { name: "Bournemouth", rating: 4.0, women: false, national: false },
  { name: "Brighton & Hove Albion", rating: 4.0, women: false, national: false },
  { name: "Crystal Palace", rating: 4.0, women: false, national: false },
  { name: "West Ham", rating: 4.0, women: false, national: false },
  { name: "AS Monaco", rating: 4.0, women: false, national: false },
  { name: "Olympique de Marseille", rating: 4.0, women: false, national: false },
  { name: "Eintracht Frankfurt", rating: 4.0, women: false, national: false },
  { name: "SL Benfica", rating: 4.0, women: false, national: false },
  { name: "Al Hilal", rating: 4.0, women: false, national: false },
  { name: "Real Betis", rating: 4.0, women: false, national: false },
  { name: "Real Sociedad", rating: 4.0, women: false, national: false },
  { name: "Villareal", rating: 4.0, women: false, national: false },
  { name: "Fenerbahçe Istanbul", rating: 4.0, women: false, national: false },
  { name: "Eintracht Frankfurt (W)", rating: 4.0, women: true, national: false },
  { name: "Atlético Madrid (W)", rating: 4.0, women: true, national: false },
  { name: "NJ/NY Gotham (W)", rating: 4.0, women: true, national: false },
  { name: "Orlando Pride (W)", rating: 4.0, women: true, national: false },
  { name: "Washington Spirit (W)", rating: 4.0, women: true, national: false },
  { name: "Brentford", rating: 4.0, women: false, national: false },
  { name: "Fulham", rating: 4.0, women: false, national: false },
  { name: "LOSC Lille", rating: 4.0, women: false, national: false },
  { name: "VfB Stuttgart", rating: 4.0, women: false, national: false },
  { name: "VfL Wolfsburg", rating: 4.0, women: false, national: false },
  { name: "Bologna", rating: 4.0, women: false, national: false },
  { name: "Fiorentina", rating: 4.0, women: false, national: false },
  { name: "Girona", rating: 4.0, women: false, national: false },
  { name: "Mallorca", rating: 4.0, women: false, national: false },
  { name: "Rayo Vallecano", rating: 4.0, women: false, national: false },
  { name: "Aston Villa (W)", rating: 4.0, women: true, national: false },
  { name: "Angel City (W)", rating: 4.0, women: true, national: false },
  { name: "Portland Thorns (W)", rating: 4.0, women: true, national: false },
  { name: "Paris FC", rating: 4.0, women: false, national: false },
  { name: "River Plate", rating: 4.0, women: false, national: false },
  { name: "Everton", rating: 4.0, women: false, national: false },
  { name: "Leeds United", rating: 4.0, women: false, national: false },
  { name: "Wolverhampton", rating: 4.0, women: false, national: false },
  { name: "OGC Nice", rating: 4.0, women: false, national: false },
  { name: "Olympique Lyonnais", rating: 4.0, women: false, national: false },
  { name: "Stade Rennais FC", rating: 4.0, women: false, national: false },
  { name: "Borussia Mönchengladbach", rating: 4.0, women: false, national: false },
  { name: "SC Freiburg", rating: 4.0, women: false, national: false },
  { name: "Torino", rating: 4.0, women: false, national: false },
  { name: "PSV", rating: 4.0, women: false, national: false },
  { name: "FC Porto", rating: 4.0, women: false, national: false },
  { name: "Al Nassr", rating: 4.0, women: false, national: false },
  { name: "Celta Vigo", rating: 4.0, women: false, national: false },
  { name: "Getafe", rating: 4.0, women: false, national: false },
  { name: "Osasuna", rating: 4.0, women: false, national: false },
  { name: "Sevilla", rating: 4.0, women: false, national: false },
  { name: "Valencia", rating: 4.0, women: false, national: false },
  { name: "Beşiktaş Istanbul", rating: 4.0, women: false, national: false },
  { name: "Everton (W)", rating: 4.0, women: true, national: false },
  { name: "London City Lionesses (W)", rating: 4.0, women: true, national: false },
  { name: "Tottenham (W)", rating: 4.0, women: true, national: false },
  { name: "West Ham (W)", rating: 4.0, women: true, national: false },
  { name: "Houston Dash (W)", rating: 4.0, women: true, national: false },
  { name: "San Diego Wave (W)", rating: 4.0, women: true, national: false },
  { name: "Seattle Reign (W)", rating: 4.0, women: true, national: false },
  { name: "Fleury", rating: 4.0, women: false, national: false },
  { name: "Boca Juniors", rating: 4.0, women: false, national: false },
  { name: "1899 Hoffenheim", rating: 4.0, women: false, national: false },
  { name: "FC Augsburg", rating: 4.0, women: false, national: false },
  { name: "Mainz 05", rating: 4.0, women: false, national: false },
  { name: "SV Werder Bremen", rating: 4.0, women: false, national: false },
  { name: "Como", rating: 4.0, women: false, national: false },
  { name: "Ajax", rating: 4.0, women: false, national: false },
  { name: "Feyenoord", rating: 4.0, women: false, national: false },
  { name: "Sporting de Braga", rating: 4.0, women: false, national: false },
  { name: "Al Ittihad", rating: 4.0, women: false, national: false },
  { name: "Celtic", rating: 4.0, women: false, national: false },
  { name: "Brighton & Hove Albion (W)", rating: 4.0, women: true, national: false },
  { name: "Bayer Leverkusen (W)", rating: 4.0, women: true, national: false },
  { name: "Athletic Bilbao (W)", rating: 4.0, women: true, national: false },
  { name: "Real Sociedad (W)", rating: 4.0, women: true, national: false },
  { name: "Chicago Red Stars (W)", rating: 4.0, women: true, national: false },
  { name: "North Carolina Courage (W)", rating: 4.0, women: true, national: false },
  { name: "Racing Louisville (W)", rating: 4.0, women: true, national: false },
  { name: "Utah Royals (W)", rating: 4.0, women: true, national: false },
  { name: "Racing Club", rating: 3.5, women: false, national: false },
  { name: "Club Brugge", rating: 3.5, women: false, national: false },
  { name: "Burnley", rating: 3.5, women: false, national: false },
  { name: "Sunderland", rating: 3.5, women: false, national: false },
  { name: "Ipswich Town", rating: 3.5, women: false, national: false },
  { name: "Leicester City", rating: 3.5, women: false, national: false },
  { name: "Racing Club de Lens", rating: 3.5, women: false, national: false },
  { name: "RC Strasbourg Alsace", rating: 3.5, women: false, national: false },
  { name: "Union Berlin", rating: 3.5, women: false, national: false },
  { name: "Al Ahli", rating: 3.5, women: false, national: false },
  { name: "Espanyol", rating: 3.5, women: false, national: false },
  { name: "Trabzonspor", rating: 3.5, women: false, national: false },
  { name: "1. FC Köln (W)", rating: 3.5, women: true, national: false },
  { name: "RB Leipzig (W)", rating: 3.5, women: true, national: false },
  { name: "Bay FC (W)", rating: 3.5, women: true, national: false },
  { name: "Estudiantes", rating: 3.5, women: false, national: false },
  { name: "Sarmiento", rating: 3.5, women: false, national: false },
  { name: "Talleres", rating: 3.5, women: false, national: false },
  { name: "Vélez Sarsfield", rating: 3.5, women: false, national: false },
  { name: "Genk", rating: 3.5, women: false, national: false },
  { name: "Union SG", rating: 3.5, women: false, national: false },
  { name: "Southampton", rating: 3.5, women: false, national: false },
  { name: "Toulouse FC", rating: 3.5, women: false, national: false },
  { name: "1. FC Köln", rating: 3.5, women: false, national: false },
  { name: "Genoa", rating: 3.5, women: false, national: false },
  { name: "Sassuolo", rating: 3.5, women: false, national: false },
  { name: "Udinese", rating: 3.5, women: false, national: false },
  { name: "AZ", rating: 3.5, women: false, national: false },
  { name: "Al-Qadsiah", rating: 3.5, women: false, national: false },
  { name: "Rangers", rating: 3.5, women: false, national: false },
  { name: "Alavés", rating: 3.5, women: false, national: false },
  { name: "Inter Miami CF", rating: 3.5, women: false, national: false },
  { name: "Liverpool (W)", rating: 3.5, women: true, national: false },
  { name: "1899 Hoffenheim (W)", rating: 3.5, women: true, national: false },
  { name: "Rot-Weiss Essen (W)", rating: 3.5, women: true, national: false },
  { name: "SC Freiburg (W)", rating: 3.5, women: true, national: false },
  { name: "SV Werder Bremen (W)", rating: 3.5, women: true, national: false },
  { name: "Levante Badalona (W)", rating: 3.5, women: true, national: false },
  { name: "Madrid CFF (W)", rating: 3.5, women: true, national: false },
  { name: "Sevilla (W)", rating: 3.5, women: true, national: false },
  { name: "UD Tenerife (W)", rating: 3.5, women: true, national: false },
  { name: "Belgrano", rating: 3.5, women: false, national: false },
  { name: "Lanús", rating: 3.5, women: false, national: false },
  { name: "Rosario Central", rating: 3.5, women: false, national: false },
  { name: "R.S.C Anderlecht", rating: 3.5, women: false, national: false },
  { name: "FC København", rating: 3.5, women: false, national: false },
  { name: "Birmingham City", rating: 3.5, women: false, national: false },
  { name: "Auxerre", rating: 3.5, women: false, national: false },
  { name: "FC Nantes", rating: 3.5, women: false, national: false },
  { name: "Stade Brestois 29", rating: 3.5, women: false, national: false },
  { name: "Stade de Reims", rating: 3.5, women: false, national: false },
  { name: "1. FC Heidenheim", rating: 3.5, women: false, national: false },
  { name: "Hamburger SV", rating: 3.5, women: false, national: false },
  { name: "Cagliari", rating: 3.5, women: false, national: false },
  { name: "Cremonese", rating: 3.5, women: false, national: false },
  { name: "Hellas Verona", rating: 3.5, women: false, national: false },
  { name: "Lecce", rating: 3.5, women: false, national: false },
  { name: "Parma", rating: 3.5, women: false, national: false },
  { name: "Palermo", rating: 3.5, women: false, national: false },
  { name: "Twente", rating: 3.5, women: false, national: false },
  { name: "Levante", rating: 3.5, women: false, national: false },
  { name: "Real Oviedo", rating: 3.5, women: false, national: false },
  { name: "Almería", rating: 3.5, women: false, national: false },
  { name: "Istanbul Başakşehir FK", rating: 3.5, women: false, national: false },
  { name: "Union Berlin (W)", rating: 3.5, women: true, national: false },
  { name: "Le Havre", rating: 3.5, women: false, national: false },
  { name: "Montpellier HSC", rating: 3.5, women: false, national: false },
  { name: "Nantes", rating: 3.5, women: false, national: false },
  { name: "Argentinos Jrs", rating: 3.5, women: false, national: false },
  { name: "Huracán", rating: 3.5, women: false, national: false },
  { name: "Independiente", rating: 3.5, women: false, national: false },
  { name: "Newell's", rating: 3.5, women: false, national: false },
  { name: "FC Red Bull Salzburg", rating: 3.5, women: false, national: false },
  { name: "FC Midtjylland", rating: 3.5, women: false, national: false },
  { name: "Bristol City", rating: 3.5, women: false, national: false },
  { name: "Coventry City", rating: 3.5, women: false, national: false },
  { name: "Middlesbrough", rating: 3.5, women: false, national: false },
  { name: "Norwich", rating: 3.5, women: false, national: false },
  { name: "Sheffield United", rating: 3.5, women: false, national: false },
  { name: "Angers SCO", rating: 3.5, women: false, national: false },
  { name: "FC Lorient", rating: 3.5, women: false, national: false },
  { name: "FC St. Pauli", rating: 3.5, women: false, national: false },
  { name: "VfL Bochum", rating: 3.5, women: false, national: false },
  { name: "Monza", rating: 3.5, women: false, national: false },
  { name: "Venezia", rating: 3.5, women: false, national: false },
  { name: "FC Utrecht", rating: 3.5, women: false, national: false },
  { name: "Vitória de Guimarães", rating: 3.5, women: false, national: false },
  { name: "Las Palmas", rating: 3.5, women: false, national: false },
  { name: "BSC Young Boys", rating: 3.5, women: false, national: false },
  { name: "FC Basel", rating: 3.5, women: false, national: false },
  { name: "Eyüpspor", rating: 3.5, women: false, national: false },
  { name: "Samsunspor", rating: 3.5, women: false, national: false },
  { name: "FC Cincinnati", rating: 3.5, women: false, national: false },
  { name: "Seattle Sounders FC", rating: 3.5, women: false, national: false },
  { name: "Leicester City (W)", rating: 3.5, women: true, national: false },
  { name: "Deportivo Abanca (W)", rating: 3.5, women: true, national: false },
  { name: "Dijon", rating: 3.5, women: false, national: false },
  { name: "Atlético Tucumán", rating: 3.0, women: false, national: false },
  { name: "Defensa y Justicia", rating: 3.0, women: false, national: false },
  { name: "Gimnasia", rating: 3.0, women: false, national: false },
  { name: "Godoy Cruz", rating: 3.0, women: false, national: false },
  { name: "Gent", rating: 3.0, women: false, national: false },
  { name: "KV Westerlo", rating: 3.0, women: false, national: false },
  { name: "Mechelen", rating: 3.0, women: false, national: false },
  { name: "Royal Antwerp", rating: 3.0, women: false, national: false },
  { name: "Hull City", rating: 3.0, women: false, national: false },
  { name: "Millwall", rating: 3.0, women: false, national: false },
  { name: "Queens Park Rangers", rating: 3.0, women: false, national: false },
  { name: "Stoke City", rating: 3.0, women: false, national: false },
  { name: "Watford", rating: 3.0, women: false, national: false },
  { name: "West Bromwich Albion", rating: 3.0, women: false, national: false },
  { name: "Luton Town", rating: 3.0, women: false, national: false },
  { name: "FC Metz", rating: 3.0, women: false, national: false },
  { name: "Havre AC", rating: 3.0, women: false, national: false },
  { name: "AS Saint-Étienne", rating: 3.0, women: false, national: false },
  { name: "Darmstadt 98", rating: 3.0, women: false, national: false },
  { name: "Hertha BSC", rating: 3.0, women: false, national: false },
  { name: "Holstein Kiel", rating: 3.0, women: false, national: false },
  { name: "Pisa", rating: 3.0, women: false, national: false },
  { name: "NEC Nijmegen", rating: 3.0, women: false, national: false },
  { name: "Bodø/Glimt", rating: 3.0, women: false, national: false },
  { name: "Lech Poznań", rating: 3.0, women: false, national: false },
  { name: "Raków Częstochowa", rating: 3.0, women: false, national: false },
  { name: "Estoril", rating: 3.0, women: false, national: false },
  { name: "Famalicão", rating: 3.0, women: false, national: false },
  { name: "Santa Clara", rating: 3.0, women: false, national: false },
  { name: "FCSB", rating: 3.0, women: false, national: false },
  { name: "Elche", rating: 3.0, women: false, national: false },
  { name: "Cádiz", rating: 3.0, women: false, national: false },
  { name: "Deportivo La Coruña", rating: 3.0, women: false, national: false },
  { name: "Leganés", rating: 3.0, women: false, national: false },
  { name: "Sporting de Gijón", rating: 3.0, women: false, national: false },
  { name: "Zaragoza", rating: 3.0, women: false, national: false },
  { name: "Malmö FF", rating: 3.0, women: false, national: false },
  { name: "Atlanta United", rating: 3.0, women: false, national: false },
  { name: "Charlotte FC", rating: 3.0, women: false, national: false },
  { name: "Columbus Crew SC", rating: 3.0, women: false, national: false },
  { name: "LA Galaxy", rating: 3.0, women: false, national: false },
  { name: "Los Angeles FC", rating: 3.0, women: false, national: false },
  { name: "Vancouver Whitecaps FC", rating: 3.0, women: false, national: false },
  { name: "1. FC Nürnberg (W)", rating: 3.0, women: true, national: false },
  { name: "Hamburger SV (W)", rating: 3.0, women: true, national: false },
  { name: "Espanyol (W)", rating: 3.0, women: true, national: false },
  { name: "Granada (W)", rating: 3.0, women: true, national: false },
  { name: "Levante UD (W)", rating: 3.0, women: true, national: false },
  { name: "Banfield", rating: 3.0, women: false, national: false },
  { name: "Barracas Central", rating: 3.0, women: false, national: false },
  { name: "Central Córdoba", rating: 3.0, women: false, national: false },
  { name: "Independiente Rivadavia", rating: 3.0, women: false, national: false },
  { name: "Instituto", rating: 3.0, women: false, national: false },
  { name: "Platense", rating: 3.0, women: false, national: false },
  { name: "San Lorenzo", rating: 3.0, women: false, national: false },
  { name: "Unión", rating: 3.0, women: false, national: false },
  { name: "FK Austria Wien", rating: 3.0, women: false, national: false },
  { name: "SK Rapid Wien", rating: 3.0, women: false, national: false },
  { name: "SK Sturm Graz", rating: 3.0, women: false, national: false },
  { name: "Charleroi", rating: 3.0, women: false, national: false },
  { name: "Leuven", rating: 3.0, women: false, national: false },
  { name: "Standard Liège", rating: 3.0, women: false, national: false },
  { name: "Aarhus GF", rating: 3.0, women: false, national: false },
  { name: "Blackburn Rovers", rating: 3.0, women: false, national: false },
  { name: "Derby County", rating: 3.0, women: false, national: false },
  { name: "Oxford United", rating: 3.0, women: false, national: false },
  { name: "Preston North End", rating: 3.0, women: false, national: false },
  { name: "Swansea City", rating: 3.0, women: false, national: false },
  { name: "Wrexham", rating: 3.0, women: false, national: false },
  { name: "1. FC Kaiserslautern", rating: 3.0, women: false, national: false },
  { name: "Fortuna Düsseldorf", rating: 3.0, women: false, national: false },
  { name: "Hannover 96", rating: 3.0, women: false, national: false },
  { name: "Modena", rating: 3.0, women: false, national: false },
  { name: "Sampdoria", rating: 3.0, women: false, national: false },
  { name: "Spezia", rating: 3.0, women: false, national: false },
  { name: "Ulsan Hyundai", rating: 3.0, women: false, national: false },
  { name: "Go Ahead Eagles", rating: 3.0, women: false, national: false },
  { name: "Molde", rating: 3.0, women: false, national: false },
  { name: "Legia Warszawa", rating: 3.0, women: false, national: false },
  { name: "Arouca", rating: 3.0, women: false, national: false },
  { name: "Casa Pia", rating: 3.0, women: false, national: false },
  { name: "Gil Vicente", rating: 3.0, women: false, national: false },
  { name: "Rio Ave", rating: 3.0, women: false, national: false },
  { name: "Al Taawoun", rating: 3.0, women: false, national: false },
  { name: "Ettifaq FC", rating: 3.0, women: false, national: false },
  { name: "Neom", rating: 3.0, women: false, national: false },
  { name: "Córdoba CF", rating: 3.0, women: false, national: false },
  { name: "Eibar", rating: 3.0, women: false, national: false },
  { name: "Racing Santander", rating: 3.0, women: false, national: false },
  { name: "Valladolid", rating: 3.0, women: false, national: false },
  { name: "FC Lugano", rating: 3.0, women: false, national: false },
  { name: "FC St. Gallen", rating: 3.0, women: false, national: false },
  { name: "Servette FC", rating: 3.0, women: false, national: false },
  { name: "Alanyaspor", rating: 3.0, women: false, national: false },
  { name: "Gazişehir Gaziantep FK", rating: 3.0, women: false, national: false },
  { name: "Konyaspor", rating: 3.0, women: false, national: false },
  { name: "Çaykur Rizespor", rating: 3.0, women: false, national: false },
  { name: "Austin FC", rating: 3.0, women: false, national: false },
  { name: "Chicago Fire", rating: 3.0, women: false, national: false },
  { name: "Minnesota United FC", rating: 3.0, women: false, national: false },
  { name: "Nashville SC", rating: 3.0, women: false, national: false },
  { name: "New England Revolution", rating: 3.0, women: false, national: false },
  { name: "New York Red Bulls", rating: 3.0, women: false, national: false },
  { name: "Orlando City", rating: 3.0, women: false, national: false },
  { name: "Portland Timbers", rating: 3.0, women: false, national: false },
  { name: "San Diego", rating: 3.0, women: false, national: false },
  { name: "San Jose Earthquakes", rating: 3.0, women: false, national: false },
  { name: "Sporting Kansas City", rating: 3.0, women: false, national: false },
  { name: "St Louis City FC", rating: 3.0, women: false, national: false },
  { name: "Carl Zeiss Jena (W)", rating: 3.0, women: true, national: false },
  { name: "Aldovidi", rating: 2.5, women: false, national: false },
  { name: "Tigre", rating: 2.5, women: false, national: false },
  { name: "LASK", rating: 2.5, women: false, national: false },
  { name: "Wolfsberger AC", rating: 2.5, women: false, national: false },
  { name: "Shanghai Greenland Shenhua", rating: 2.5, women: false, national: false },
  { name: "Shanghai Port", rating: 2.5, women: false, national: false },
  { name: "Brøndby IF", rating: 2.5, women: false, national: false },
  { name: "Randers FC", rating: 2.5, women: false, national: false },
  { name: "Charlton Athletic", rating: 2.5, women: false, national: false },
  { name: "Portsmouth", rating: 2.5, women: false, national: false },
  { name: "Cardiff City", rating: 2.5, women: false, national: false },
  { name: "1. FC Magdeburg", rating: 2.5, women: false, national: false },
  { name: "1. FC Nürnberg", rating: 2.5, women: false, national: false },
  { name: "FC Schalke 04", rating: 2.5, women: false, national: false },
  { name: "Greuther Fürth", rating: 2.5, women: false, national: false },
  { name: "Karlsruher SC", rating: 2.5, women: false, national: false },
  { name: "SC Paderborn", rating: 2.5, women: false, national: false },
  { name: "SV Elversberg", rating: 2.5, women: false, national: false },
  { name: "Daejeon Citizen", rating: 2.5, women: false, national: false },
  { name: "FC Seoul", rating: 2.5, women: false, national: false },
  { name: "Jeonbuk Hyundai Motors", rating: 2.5, women: false, national: false },
  { name: "Pohang Steelers", rating: 2.5, women: false, national: false },
  { name: "Fortuna Sittard", rating: 2.5, women: false, national: false },
  { name: "Rosenborg", rating: 2.5, women: false, national: false },
  { name: "SK Brann", rating: 2.5, women: false, national: false },
  { name: "Viking", rating: 2.5, women: false, national: false },
  { name: "Jagiellonia Białystok", rating: 2.5, women: false, national: false },
  { name: "Pogoń Szczecin", rating: 2.5, women: false, national: false },
  { name: "AVS", rating: 2.5, women: false, national: false },
  { name: "CD Nacional", rating: 2.5, women: false, national: false },
  { name: "Estrela Amadora", rating: 2.5, women: false, national: false },
  { name: "Moreirense", rating: 2.5, women: false, national: false },
  { name: "CFR Cluj", rating: 2.5, women: false, national: false },
  { name: "Universitatea Craiova", rating: 2.5, women: false, national: false },
  { name: "Heart of Midlothian", rating: 2.5, women: false, national: false },
  { name: "Hibernian", rating: 2.5, women: false, national: false },
  { name: "Albacete", rating: 2.5, women: false, national: false },
  { name: "Burgos", rating: 2.5, women: false, national: false },
  { name: "Granada", rating: 2.5, women: false, national: false },
  { name: "Huesca", rating: 2.5, women: false, national: false },
  { name: "AIK", rating: 2.5, women: false, national: false },
  { name: "BK Häcken", rating: 2.5, women: false, national: false },
  { name: "Djurgårdens IF", rating: 2.5, women: false, national: false },
  { name: "Hammarby IF", rating: 2.5, women: false, national: false },
  { name: "IF Elfsborg", rating: 2.5, women: false, national: false },
  { name: "Antalyaspor", rating: 2.5, women: false, national: false },
  { name: "Kasımpaşa Istanbul", rating: 2.5, women: false, national: false },
  { name: "Kocaelispor", rating: 2.5, women: false, national: false },
  { name: "FC Dallas", rating: 2.5, women: false, national: false },
  { name: "Houston Dynamo", rating: 2.5, women: false, national: false },
  { name: "New York City FC", rating: 2.5, women: false, national: false },
  { name: "Philadelphia Union", rating: 2.5, women: false, national: false },
  { name: "Real Salt Lake", rating: 2.5, women: false, national: false },
  { name: "Cercle Brugge", rating: 2.5, women: false, national: false },
  { name: "Dender EH", rating: 2.5, women: false, national: false },
  { name: "Sint-Truiden", rating: 2.5, women: false, national: false },
  { name: "Beijing Sinobo Guoan", rating: 2.5, women: false, national: false },
  { name: "FC Nordsjælland", rating: 2.5, women: false, national: false },
  { name: "Silkeborg IF", rating: 2.5, women: false, national: false },
  { name: "Huddersfield Town", rating: 2.5, women: false, national: false },
  { name: "En Avant Guingamp", rating: 2.5, women: false, national: false },
  { name: "Laval MFC", rating: 2.5, women: false, national: false },
  { name: "Dynamo Dresden", rating: 2.5, women: false, national: false },
  { name: "Eintracht Braunschweig", rating: 2.5, women: false, national: false },
  { name: "Preußen Münster", rating: 2.5, women: false, national: false },
  { name: "Bari", rating: 2.5, women: false, national: false },
  { name: "Carrarese Calcio", rating: 2.5, women: false, national: false },
  { name: "Catanzaro", rating: 2.5, women: false, national: false },
  { name: "Empoli", rating: 2.5, women: false, national: false },
  { name: "Mantova", rating: 2.5, women: false, national: false },
  { name: "Padova", rating: 2.5, women: false, national: false },
  { name: "Südtirol", rating: 2.5, women: false, national: false },
  { name: "SC Heerenveen", rating: 2.5, women: false, national: false },
  { name: "Sparta Rotterdam", rating: 2.5, women: false, national: false },
  { name: "Cracovia", rating: 2.5, women: false, national: false },
  { name: "Górnik Zabrze", rating: 2.5, women: false, national: false },
  { name: "Widzew Łódź", rating: 2.5, women: false, national: false },
  { name: "Tondela", rating: 2.5, women: false, national: false },
  { name: "Dinamo Bucuresti", rating: 2.5, women: false, national: false },
  { name: "Rapid București", rating: 2.5, women: false, national: false },
  { name: "Universitatea Cluj", rating: 2.5, women: false, national: false },
  { name: "Aberdeen", rating: 2.5, women: false, national: false },
  { name: "Castellón", rating: 2.5, women: false, national: false },
  { name: "Málaga", rating: 2.5, women: false, national: false },
  { name: "Mjällby AI", rating: 2.5, women: false, national: false },
  { name: "FC Lausanne-Sport", rating: 2.5, women: false, national: false },
  { name: "FC Luzern", rating: 2.5, women: false, national: false },
  { name: "FC Sion", rating: 2.5, women: false, national: false },
  { name: "Gençlerbirliği", rating: 2.5, women: false, national: false },
  { name: "Göztepe", rating: 2.5, women: false, national: false },
  { name: "Colorado Rapids", rating: 2.5, women: false, national: false },
  { name: "D.C. United", rating: 2.5, women: false, national: false },
  { name: "Toronto FC", rating: 2.5, women: false, national: false },
  { name: "SD Eibar (W)", rating: 2.5, women: true, national: false },
  { name: "San Martín", rating: 2.0, women: false, national: false },
  { name: "La Louvière", rating: 2.0, women: false, national: false },
  { name: "Zulte Waregem", rating: 2.0, women: false, national: false },
  { name: "Chengdu Rongcheng", rating: 2.0, women: false, national: false },
  { name: "Shandong Luneng Taishan", rating: 2.0, women: false, national: false },
  { name: "OB Odense", rating: 2.0, women: false, national: false },
  { name: "Viborg FF", rating: 2.0, women: false, national: false },
  { name: "Sheffield Wednesday", rating: 2.0, women: false, national: false },
  { name: "Blackpool", rating: 2.0, women: false, national: false },
  { name: "Bolton Wanderers", rating: 2.0, women: false, national: false },
  { name: "Plymouth Argyle", rating: 2.0, women: false, national: false },
  { name: "Wycombe Wanderers", rating: 2.0, women: false, national: false },
  { name: "Clermont Foot", rating: 2.0, women: false, national: false },
  { name: "Grenoble Foot 38", rating: 2.0, women: false, national: false },
  { name: "Troyes", rating: 2.0, women: false, national: false },
  { name: "Arminia Bielefeld", rating: 2.0, women: false, national: false },
  { name: "1. FC Saarbrücken", rating: 2.0, women: false, national: false },
  { name: "Hansa Rostock", rating: 2.0, women: false, national: false },
  { name: "TSV 1860 Munchen", rating: 2.0, women: false, national: false },
  { name: "Avelino", rating: 2.0, women: false, national: false },
  { name: "Cesena", rating: 2.0, women: false, national: false },
  { name: "Reggiana", rating: 2.0, women: false, national: false },
  { name: "SS Juve Stabia", rating: 2.0, women: false, national: false },
  { name: "Virtus Entella", rating: 2.0, women: false, national: false },
  { name: "FC Anyang", rating: 2.0, women: false, national: false },
  { name: "Groningen", rating: 2.0, women: false, national: false },
  { name: "Heracles Almelo", rating: 2.0, women: false, national: false },
  { name: "NAC Breda", rating: 2.0, women: false, national: false },
  { name: "PEC Zwolle", rating: 2.0, women: false, national: false },
  { name: "Sarpsborg 08", rating: 2.0, women: false, national: false },
  { name: "Motor Lublin", rating: 2.0, women: false, national: false },
  { name: "Piast Gliwice", rating: 2.0, women: false, national: false },
  { name: "Radomiak Radom", rating: 2.0, women: false, national: false },
  { name: "Al Shabab", rating: 2.0, women: false, national: false },
  { name: "IFK Göteborg", rating: 2.0, women: false, national: false },
  { name: "FC Zürich", rating: 2.0, women: false, national: false },
  { name: "Deportivo Riestra", rating: 2.0, women: false, national: false },
  { name: "Blau-Weiss Linz", rating: 2.0, women: false, national: false },
  { name: "SCR Altach", rating: 2.0, women: false, national: false },
  { name: "Barnsley", rating: 2.0, women: false, national: false },
  { name: "Leyton Orient", rating: 2.0, women: false, national: false },
  { name: "Reading", rating: 2.0, women: false, national: false },
  { name: "Rotherham United", rating: 2.0, women: false, national: false },
  { name: "Stockport County", rating: 2.0, women: false, national: false },
  { name: "Wigan Athletic", rating: 2.0, women: false, national: false },
  { name: "Beauleroix FC", rating: 2.0, women: false, national: false },
  { name: "FC Annecy", rating: 2.0, women: false, national: false },
  { name: "Pau FC", rating: 2.0, women: false, national: false },
  { name: "Red Star FC", rating: 2.0, women: false, national: false },
  { name: "USL Dunkerque", rating: 2.0, women: false, national: false },
  { name: "Rot-Weiss Essen", rating: 2.0, women: false, national: false },
  { name: "VfL Osnabrück", rating: 2.0, women: false, national: false },
  { name: "Wehen Wiesbaden", rating: 2.0, women: false, national: false },
  { name: "Frosione", rating: 2.0, women: false, national: false },
  { name: "Pescara", rating: 2.0, women: false, national: false },
  { name: "Daegu FC", rating: 2.0, women: false, national: false },
  { name: "Gangwon FC", rating: 2.0, women: false, national: false },
  { name: "Gimcheon Sangmu", rating: 2.0, women: false, national: false },
  { name: "Jeju United", rating: 2.0, women: false, national: false },
  { name: "Suwon FC", rating: 2.0, women: false, national: false },
  { name: "Excelsior", rating: 2.0, women: false, national: false },
  { name: "FC Volendam", rating: 2.0, women: false, national: false },
  { name: "Fredrikstad", rating: 2.0, women: false, national: false },
  { name: "Strømsgodset", rating: 2.0, women: false, national: false },
  { name: "Tromsø", rating: 2.0, women: false, national: false },
  { name: "Vålerenga", rating: 2.0, women: false, national: false },
  { name: "GKS Katowic", rating: 2.0, women: false, national: false },
  { name: "Korona Kielce", rating: 2.0, women: false, national: false },
  { name: "Lechia Gdańsk", rating: 2.0, women: false, national: false },
  { name: "Zagłębie Lubin", rating: 2.0, women: false, national: false },
  { name: "Alverca", rating: 2.0, women: false, national: false },
  { name: "Botoșani", rating: 2.0, women: false, national: false },
  { name: "Farul Constanța", rating: 2.0, women: false, national: false },
  { name: "FC Hermannstadt", rating: 2.0, women: false, national: false },
  { name: "FC Petrolul", rating: 2.0, women: false, national: false },
  { name: "UTA Arad", rating: 2.0, women: false, national: false },
  { name: "Al Khaleej", rating: 2.0, women: false, national: false },
  { name: "Motherwell", rating: 2.0, women: false, national: false },
  { name: "Andorra", rating: 2.0, women: false, national: false },
  { name: "Ceuta", rating: 2.0, women: false, national: false },
  { name: "Cultural Leonesa", rating: 2.0, women: false, national: false },
  { name: "GAIS", rating: 2.0, women: false, national: false },
  { name: "IF Brommapojkarna", rating: 2.0, women: false, national: false },
  { name: "IFK Norrköping", rating: 2.0, women: false, national: false },
  { name: "IK Sirius", rating: 2.0, women: false, national: false },
  { name: "Fatih Karagümrük", rating: 2.0, women: false, national: false },
  { name: "Kayserispor", rating: 2.0, women: false, national: false },
  { name: "CF Montréal", rating: 2.0, women: false, national: false },
  { name: "Alhama (W)", rating: 2.0, women: true, national: false },
  { name: "Auckland FC", rating: 1.5, women: false, national: false },
  { name: "WS Wanderers", rating: 1.5, women: false, national: false },
  { name: "Grazer AK", rating: 1.5, women: false, national: false },
  { name: "SV Ried", rating: 1.5, women: false, national: false },
  { name: "TSV Hartberg", rating: 1.5, women: false, national: false },
  { name: "WSG Tirol", rating: 1.5, women: false, national: false },
  { name: "Wuhan 3 Towns", rating: 1.5, women: false, national: false },
  { name: "Zhejiang Pro", rating: 1.5, women: false, national: false },
  { name: "SønderjyskE Fodbold", rating: 1.5, women: false, national: false },
  { name: "Vejle Boldklub", rating: 1.5, women: false, national: false },
  { name: "Lincoln City", rating: 1.5, women: false, national: false },
  { name: "Mansfield Town", rating: 1.5, women: false, national: false },
  { name: "Port Vale", rating: 1.5, women: false, national: false },
  { name: "Stevenage", rating: 1.5, women: false, national: false },
  { name: "Milton Keynes Dons", rating: 1.5, women: false, national: false },
  { name: "Amiens SC", rating: 1.5, women: false, national: false },
  { name: "Le Mans", rating: 1.5, women: false, national: false },
  { name: "Rodez Averyron", rating: 1.5, women: false, national: false },
  { name: "SC Bastia", rating: 1.5, women: false, national: false },
  { name: "Alemannia Aachen", rating: 1.5, women: false, national: false },
  { name: "Energie Cottbus", rating: 1.5, women: false, national: false },
  { name: "Erzgebirge Aue", rating: 1.5, women: false, national: false },
  { name: "FC Ingolstadt 04", rating: 1.5, women: false, national: false },
  { name: "Jahn Regensburg", rating: 1.5, women: false, national: false },
  { name: "SSV Ulm", rating: 1.5, women: false, national: false },
  { name: "SV Waldhof Mannheim", rating: 1.5, women: false, national: false },
  { name: "ATK Mohun Bagan", rating: 1.5, women: false, national: false },
  { name: "Gwangju", rating: 1.5, women: false, national: false },
  { name: "Haugesund", rating: 1.5, women: false, national: false },
  { name: "KFUM Oslo", rating: 1.5, women: false, national: false },
  { name: "Sandefjord", rating: 1.5, women: false, national: false },
  { name: "Bruk-Bet Termalica", rating: 1.5, women: false, national: false },
  { name: "Otelul Galati", rating: 1.5, women: false, national: false },
  { name: "Al Okhdood", rating: 1.5, women: false, national: false },
  { name: "Al Riyadh", rating: 1.5, women: false, national: false },
  { name: "Dundee United", rating: 1.5, women: false, national: false },
  { name: "Kilmarnock", rating: 1.5, women: false, national: false },
  { name: "Livingston", rating: 1.5, women: false, national: false },
  { name: "FC Winterthur", rating: 1.5, women: false, national: false },
  { name: "Grasshopper", rating: 1.5, women: false, national: false },
  { name: "Thun", rating: 1.5, women: false, national: false },
  { name: "DUX Logroño (W)", rating: 1.5, women: true, national: false },
  { name: "Melbourne City", rating: 1.5, women: false, national: false },
  { name: "Melbourne Victory", rating: 1.5, women: false, national: false },
  { name: "Perth Glory", rating: 1.5, women: false, national: false },
  { name: "Dalian Yingbo", rating: 1.5, women: false, national: false },
  { name: "Tianjin TEDA", rating: 1.5, women: false, national: false },
  { name: "Yunnan Yukun", rating: 1.5, women: false, national: false },
  { name: "Bradford City", rating: 1.5, women: false, national: false },
  { name: "Burton Albion", rating: 1.5, women: false, national: false },
  { name: "Doncaster", rating: 1.5, women: false, national: false },
  { name: "Exeter City", rating: 1.5, women: false, national: false },
  { name: "Northampton Town", rating: 1.5, women: false, national: false },
  { name: "Peterborough", rating: 1.5, women: false, national: false },
  { name: "Bristol Rovers", rating: 1.5, women: false, national: false },
  { name: "Cambridge United", rating: 1.5, women: false, national: false },
  { name: "Notts County", rating: 1.5, women: false, national: false },
  { name: "Shrewsbury Town", rating: 1.5, women: false, national: false },
  { name: "Nancy", rating: 1.5, women: false, national: false },
  { name: "1. FC Schweinfurt", rating: 1.5, women: false, national: false },
  { name: "FC Viktoria Koln", rating: 1.5, women: false, national: false },
  { name: "MSV Duisburg", rating: 1.5, women: false, national: false },
  { name: "SC Verl", rating: 1.5, women: false, national: false },
  { name: "Telstar", rating: 1.5, women: false, national: false },
  { name: "Bryne", rating: 1.5, women: false, national: false },
  { name: "Hamarkameratene", rating: 1.5, women: false, national: false },
  { name: "Kristiansund", rating: 1.5, women: false, national: false },
  { name: "Arka Gdynia", rating: 1.5, women: false, national: false },
  { name: "Wisła Płock", rating: 1.5, women: false, national: false },
  { name: "Argeș Pitești", rating: 1.5, women: false, national: false },
  { name: "Unirea Slobozia", rating: 1.5, women: false, national: false },
  { name: "Al-Fateh", rating: 1.5, women: false, national: false },
  { name: "Al Fayha", rating: 1.5, women: false, national: false },
  { name: "St Mirren", rating: 1.5, women: false, national: false },
  { name: "Mirandés", rating: 1.5, women: false, national: false },
  { name: "Real Sociedad B", rating: 1.5, women: false, national: false },
  { name: "Degerfors IF", rating: 1.5, women: false, national: false },
  { name: "Halmstads BK", rating: 1.5, women: false, national: false },
  { name: "IFK Värnamo", rating: 1.5, women: false, national: false },
  { name: "Östers IF", rating: 1.5, women: false, national: false },
  { name: "Adelaide United", rating: 1.0, women: false, national: false },
  { name: "Newcastle Jets", rating: 1.0, women: false, national: false },
  { name: "Sydney FC", rating: 1.0, women: false, national: false },
  { name: "Henan Jianye", rating: 1.0, women: false, national: false },
  { name: "Quingdao Hainiu", rating: 1.0, women: false, national: false },
  { name: "Quingdao West Coast", rating: 1.0, women: false, national: false },
  { name: "Shenzhen Peng City", rating: 1.0, women: false, national: false },
  { name: "Fredericia", rating: 1.0, women: false, national: false },
  { name: "AFC Wimbledon", rating: 1.0, women: false, national: false },
  { name: "Cheltenham Town", rating: 1.0, women: false, national: false },
  { name: "Chesterfield", rating: 1.0, women: false, national: false },
  { name: "Colchester United", rating: 1.0, women: false, national: false },
  { name: "Fleetwood Town", rating: 1.0, women: false, national: false },
  { name: "Gillingham", rating: 1.0, women: false, national: false },
  { name: "Grimsby Town", rating: 1.0, women: false, national: false },
  { name: "Walsall", rating: 1.0, women: false, national: false },
  { name: "TSV Havelse", rating: 1.0, women: false, national: false },
  { name: "Odisha FC", rating: 1.0, women: false, national: false },
  { name: "Shamrock Rovers", rating: 1.0, women: false, national: false },
  { name: "St Patrick's Athletic", rating: 1.0, women: false, national: false },
  { name: "Metaloglobus București", rating: 1.0, women: false, national: false },
  { name: "Al Najma", rating: 1.0, women: false, national: false },
  { name: "Damac", rating: 1.0, women: false, national: false },
  { name: "Dundee", rating: 1.0, women: false, national: false },
  { name: "Macarthur FC", rating: 1.0, women: false, national: false },
  { name: "Changchun Yatai", rating: 1.0, women: false, national: false },
  { name: "Meizhou Hakka", rating: 1.0, women: false, national: false },
  { name: "Barnet", rating: 1.0, women: false, national: false },
  { name: "Barrow", rating: 1.0, women: false, national: false },
  { name: "Bromley", rating: 1.0, women: false, national: false },
  { name: "Crawley Town", rating: 1.0, women: false, national: false },
  { name: "Crewe Alexandra", rating: 1.0, women: false, national: false },
  { name: "Harrogate Town", rating: 1.0, women: false, national: false },
  { name: "Salford City", rating: 1.0, women: false, national: false },
  { name: "Swindon Town", rating: 1.0, women: false, national: false },
  { name: "Tranmere Rovers", rating: 1.0, women: false, national: false },
  { name: "VfB Stuttgart II", rating: 1.0, women: false, national: false },
  { name: "FC Goa", rating: 1.0, women: false, national: false },
  { name: "Derry City", rating: 1.0, women: false, national: false },
  { name: "Shelbourne", rating: 1.0, women: false, national: false },
  { name: "Csíkszereda Ciuc", rating: 1.0, women: false, national: false },
  { name: "Brisbane Roar", rating: 1.0, women: false, national: false },
  { name: "Central Coast Mariners", rating: 1.0, women: false, national: false },
  { name: "Wellington Phoenix", rating: 1.0, women: false, national: false },
  { name: "Western United", rating: 1.0, women: false, national: false },
  { name: "Oldham Athletic", rating: 1.0, women: false, national: false },
  { name: "TSG Hoffenheim II", rating: 1.0, women: false, national: false },
  { name: "Mumbai City FC", rating: 1.0, women: false, national: false },
  { name: "Bohemians", rating: 1.0, women: false, national: false },
  { name: "Al-Kholood", rating: 1.0, women: false, national: false },
  { name: "Falkirk", rating: 1.0, women: false, national: false },
  { name: "Accrington Stanley", rating: 0.5, women: false, national: false },
  { name: "Newport County", rating: 0.5, women: false, national: false },
  { name: "Bengaluru FC", rating: 0.5, women: false, national: false },
  { name: "Northeast United", rating: 0.5, women: false, national: false },
  { name: "United Tigers", rating: 0.5, women: false, national: false },
  { name: "Drogheda", rating: 0.5, women: false, national: false },
  { name: "Waterford", rating: 0.5, women: false, national: false },
  { name: "Chennaiyin FC", rating: 0.5, women: false, national: false },
  { name: "East Bengal", rating: 0.5, women: false, national: false },
  { name: "Galway United", rating: 0.5, women: false, national: false },
  { name: "Sligo Rovers", rating: 0.5, women: false, national: false },
  { name: "Al Hazem", rating: 0.5, women: false, national: false },
  { name: "Jamshedpur FC", rating: 0.5, women: false, national: false },
  { name: "Cork City", rating: 0.5, women: false, national: false },
  { name: "Kerala Blasters", rating: 0.5, women: false, national: false },
  { name: "Hyderabad FC", rating: 0.5, women: false, national: false },
  { name: "Mohammedan", rating: 0.5, women: false, national: false },
  { name: "Punjab FC", rating: 0.5, women: false, national: false },
  { name: "Argentina", rating: null, women: false, national: true },
  { name: "Croatia", rating: null, women: false, national: true },
  { name: "Czechia", rating: null, women: false, national: true },
  { name: "Denmark", rating: null, women: false, national: true },
  { name: "England", rating: null, women: false, national: true },
  { name: "Finland", rating: null, women: false, national: true },
  { name: "France", rating: null, women: false, national: true },
  { name: "Germany", rating: null, women: false, national: true },
  { name: "Ghana", rating: null, women: false, national: true },
  { name: "Hungary", rating: null, women: false, national: true },
  { name: "Iceland", rating: null, women: false, national: true },
  { name: "Ireland", rating: null, women: false, national: true },
  { name: "Italy", rating: null, women: false, national: true },
  { name: "Mexico", rating: null, women: false, national: true },
  { name: "Morocco", rating: null, women: false, national: true },
  { name: "Netherlands", rating: null, women: false, national: true },
  { name: "Northern Ireland", rating: null, women: false, national: true },
  { name: "Norway", rating: null, women: false, national: true },
  { name: "Poland", rating: null, women: false, national: true },
  { name: "Portugal", rating: null, women: false, national: true },
  { name: "Qatar", rating: null, women: false, national: true },
  { name: "Romania", rating: null, women: false, national: true },
  { name: "Scotland", rating: null, women: false, national: true },
  { name: "Spain", rating: null, women: false, national: true },
  { name: "Sweden", rating: null, women: false, national: true },
  { name: "Ukraine", rating: null, women: false, national: true },
  { name: "United States", rating: null, women: false, national: true },
  { name: "Wales", rating: null, women: false, national: true },
  { name: "Argentina (Frauen)", rating: null, women: true, national: true },
  { name: "Canada (Frauen)", rating: null, women: true, national: true },
  { name: "Denmark (Frauen)", rating: null, women: true, national: true },
  { name: "England (Frauen)", rating: null, women: true, national: true },
  { name: "Finland (Frauen)", rating: null, women: true, national: true },
  { name: "France (Frauen)", rating: null, women: true, national: true },
  { name: "Germany (Frauen)", rating: null, women: true, national: true },
  { name: "Iceland (Frauen)", rating: null, women: true, national: true },
  { name: "Mexico (Frauen)", rating: null, women: true, national: true },
  { name: "Netherlands (Frauen)", rating: null, women: true, national: true },
  { name: "Norway (Frauen)", rating: null, women: true, national: true },
  { name: "Poland (Frauen)", rating: null, women: true, national: true },
  { name: "Portugal (Frauen)", rating: null, women: true, national: true },
  { name: "Scotland (Frauen)", rating: null, women: true, national: true },
  { name: "Spain (Frauen)", rating: null, women: true, national: true },
  { name: "Sweden (Frauen)", rating: null, women: true, national: true },
  { name: "United States (Frauen)", rating: null, women: true, national: true },
];

export const FC26_TEAM_NAMES = FC26_TEAMS.map(t => t.name);
